@startuml
'https://plantuml.com/class-diagram

interface Main {
    main()
}

class WeatherService {
    +sense: sense_hat
    +location: string
    +get_data(): map[string]T
}

class MasterService {
    +master_host: string
    +master_port: string
    +master_url: string
    +record_data(): void
}

Main --> WeatherService
Main --> MasterService

@enduml